// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int counter1 = 0;
		int counter2 = 0;
		int num = Integer.parseInt(args[0]);
	    for(int i = 0;i<num;i++){
			double rand = Math.random();
			if(rand<0.5){
				counter1++;
			}
			else{
				counter2++;
			}
		}
		System.out.println("> 0.5: "+counter1);
		System.out.println("<= 0.5: "+counter2);
		System.out.println("Ratio: "+(double)counter1/counter2);
	}
}
